### ISSUE TITLE
More flexibility for templating output component

### ISSUE THREAD

**Issue by davidtheclark** [boopathi/react-svg-loader#167]
I'd love to use this module but would like to do some different things with the output component. I'm not sure what the best way to approach this would be — whether providing a slew of new options, or a templating system that would allow custom, or something else.

Here are things that I would like to do:
- Check propTypes to ensure that the user has provided `style.width` and `style.height`, which are often necessary for IE.
- Add `focusable="false"` to the every `svg` element.
- Add an `aria-labelled` attribute to the `svg` element whose value is a generated id that is used by a `<title>` element that is the first child of the `svg`, which receives `this.props.title`.

**Comment by davidtheclark** [comment]
Another possibility would be to publish the core of the Babel plugin separately — that is, the code that fixes up SVG attributes so everything works as JSX. Then people who want more flexibility can wrap this with their own code, but we benefit from collaborating on the core problem.

**Comment by davidtheclark** [comment]
As I think about this more, it seems to me that *working with a template* (instead of creating the JSX with Babel, then stringifying that) might be a good way to provide lots of flexibility. Are you interested in such a significant change? Or would you rather keep things as they are, and I'll work on making a loader with a different approach?

**Comment by boopathi** [comment]
Hi. Thanks for the great ideas. I've considered moving the babel plugin into a separate package. But haven't got enough time to spend on this loader. I'd keep the loader as it is for version 2 instead of splitting it into packages. But definitely something that I'd do in the next major version. 

And regarding the other points -

> Check propTypes to ensure that the user has provided style.width and style.height, which are often necessary for IE

Is there a more generic requirement - like adding any prop-types?

> Add focusable="false" to the every svg element

This will be too specific for one case. Isn't it?

> Add an aria-labelled attribute to the svg element whose value is a generated id that is used by a `<title>` element that is the first child of the svg, which receives this.props.title

Similar #171. Definitely something we can add for 2.x.

And for these items, PR definitely welcome.

> As I think about this more, it seems to me that working with a template (instead of creating the JSX with Babel, then stringifying that) might be a good way to provide lots of flexibility. Are you interested in such a significant change?

I don't want to change the babel generation phase to a template because templates can cause syntax errors if we miss calculate something. On the other hand, working with the AST through babel gives some level of guarantee that the generated code(if it generates without errors) will contain less bugs - at least doesn't throw a syntax error. I consider this shifting of (some possibilities mistakes) errors from runtime to compile time is important.

Thanks again for the great ideas.

**Comment by boopathi** [comment]
It's now split into 3 packages - babel-plugin, loader and cli - https://github.com/boopathi/react-svg-loader/releases/tag/v2.0.0-alpha.4

**Comment by sleexyz** [comment]
For anybody who might be looking at this and wonder how to add `focusable="false"` on every SVG element:

The following is a way to do this in your webpack config, provided you are on react-svg-loader@^2.0.0:

```js
      {
        test: /\.svg$/,
        use: [
          {
            loader: "babel-loader"
          },
          {
            loader: "react-svg-loader",
            options: {
              svgo: {
                plugins: [
                  { addAttributesToSVGElement: { attributes: [ 'focusable="false"' ] } }
                ]
              }
            }
          }
        ]
      }
```

You could do this for any attribute. For example, we needed `aria-hidden="true"` on every SVG element

**Comment by petermikitsh** [comment]
@sleexyz Thank you for sharing how to add `focusable='false'` to all SVG elements. Your configuration worked for my webpack setup.
